litrevu/urls.py
from django.contrib import admin
from django.urls import path, include
from users import urls as users_urls
from litrevu_management import urls as litrevu_urls
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include(users_urls)),
    path('', include(litrevu_urls))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
import users.views

app_name = "users"

urlpatterns = [
    path('login/', users.views.user_login, name='login'),
    path('signup/', users.views.signup, name='signup'),
    path('logout/', users.views.logout_user, name='logout'),
    path('following/', users.views.following, name='following'),
    path('following/follow/', users.views.follow_user, name='follow_user'),
    path(
        'following/follow/<unfollow>',
        users.views.follow_user,
        name='follow_user'
    ),
    path('following/block/', users.views.block_user, name='block_user'),
    path(
        'following/block/<unblock>/',
        users.views.block_user,
        name='block_user'
    ),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from litrevu import settings


class User(AbstractUser):
    """Model used to manage User system, herited from django standard User
    model"""

    def __str__(self):
        return f'{self.username}'


class UserFollows(models.Model):
    """Model used to manage following system"""
    user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="following",
    )
    followed_user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="followed_by"
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'followed_user'],
                name='unique_follow'
            )
        ]


class UserBlocked(models.Model):
    """Model used to manage blocking user system"""
    user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="user"
    )

    blocked_user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="user_blocked"
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'blocked_user'],
                name='unique_block'
            )
        ]

users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from users.models import User

USERNAME_VALIDATION_TEXT = "15 caractères maximum."
PASSWORD_VALIDATION_TEXT = "Votre mot de passe doit contenir 8 caractères minimum."
PASSWORD_2_VALIDATION_TEXT = "Ressaisissez le même mot de passe."


class SignupForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["email"].label = "Email"
        self.fields["email"].required = True
        self.fields["password1"].label = "Mot de passe"
        self.fields["password2"].label = 'Confirmer mot de passe'
        self.fields["username"].help_text = USERNAME_VALIDATION_TEXT
        self.fields["password1"].help_text = PASSWORD_VALIDATION_TEXT
        self.fields["password2"].help_text = PASSWORD_2_VALIDATION_TEXT
        for field in self.fields.values():
            field.widget.attrs.update({"class": "form-control"})

    def clean_username(self):
        username = self.cleaned_data.get("username")
        if len(username) > 15:
            raise forms.ValidationError("le nom d'utilisateur ne peut pas contenir plus de 15 caractères")
        return username

    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ["email", "username"]


class LoginForm(forms.Form):
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super().__init__(*args, **kwargs)

    username = forms.CharField(
        max_length=64,
        label="Username",
        widget=forms.TextInput(attrs={"class": "form-control"})
    )
    password = forms.CharField(
        max_length=64,
        label="Mot de passe",
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )


class FollowUserForm(forms.Form):
    username = forms.CharField(
        label='',
        max_length=64,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': "nom d'utilisateur"})
    )


class BlockUserForm(forms.Form):
    username = forms.CharField(
        max_length=64,
        label='',
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': "nom d'utilisateur"})
    )

users/views.py
from django.db import IntegrityError

from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
import users.forms
from users.models import User, UserFollows, UserBlocked
from litrevu import settings


def user_login(request):
    login_form = users.forms.LoginForm(
        request.POST if request.method == "POST" else None
    )
    login_message = ""
    if request.method == "POST" and login_form.is_valid():
        user = authenticate(
            username=login_form.cleaned_data["username"],
            password=login_form.cleaned_data["password"]
        )
        if user is not None:
            login(request, user)
            return redirect(settings.LOGIN_REDIRECT_URL)
        else:
            login_message = "identifiants invalides"
    return render(
        request,
        template_name='login.html',
        context={
            "form": login_form,
            "message": login_message,
        }
    )


def logout_user(request):
    logout(request)
    return redirect('users:login')


def signup(request):
    user_form = users.forms.SignupForm(
        request.POST if request.method == "POST" else None)
    if request.method == "POST" and user_form.is_valid():
        new_user = user_form.save()
        login(request, new_user)
        return redirect(settings.LOGIN_REDIRECT_URL)
    return render(
        request,
        'signup.html',
        {'user_form': user_form},
    )


@login_required
def following(request):
    follow_form = users.forms.FollowUserForm()
    block_form = users.forms.BlockUserForm()
    followers_relation = UserFollows.objects.filter(
        followed_user=request.user.id)
    followers_users = []
    for follower in followers_relation:
        follower_user = User.objects.get(id=follower.user_id)
        followers_users.append(follower_user)
    return render(
        request,
        template_name='following.html',
        context={
            'follow_form': follow_form,
            'block_form': block_form,
            'followers': followers_users,
        }
    )


@login_required
def follow_user(request, unfollow=False):
    try:
        user_to_manage = User.objects.get(
            username=request.POST.get("username"))
    except User.DoesNotExist:
        messages.error(
            request,
            message="Utilisateur introuvable",
            extra_tags="follow_error"
        )
        return redirect("users:following")
    if user_to_manage == request.user:
        messages.error(
            request,
            message="Vous ne pouvez pas vous suivre vous-même.",
            extra_tags="follow_error")
        return redirect("users:following")
    if UserBlocked.objects.filter(
            user=request.user,
            blocked_user=user_to_manage
    ).exists():
        messages.error(
            request,
            message="Veuillez débloquer cet utilisateur pour le suivre.",
            extra_tags="follow_error")
        return redirect("users:following")
    try:
        if unfollow:
            UserFollows.objects.get(
                user=request.user,
                followed_user=user_to_manage
            ).delete()
            return redirect("users:following")
        else:
            UserFollows.objects.create(
                followed_user=user_to_manage,
                user=request.user,
            )
            return redirect("users:following")
    except IntegrityError:
        messages.error(
            request,
            message="Vous suivez déjà cet utilisateur.",
            extra_tags="follow_error"
        )
        return redirect("users:following")
    except UserFollows.DoesNotExist:
        messages.error(
            request,
            message="Vous ne suivez pas cet utilisateur.",
            extra_tags="follow_error"
        )
        return redirect("users:following")


@login_required
def block_user(request, unblock=False):
    try:
        user_to_manage = User.objects.get(
            username=request.POST.get("username"))
    except User.DoesNotExist:
        messages.error(request, message="Utilisateur introuvable",
                       extra_tags="block_error")
        return redirect("users:following")
    if user_to_manage == request.user:
        messages.error(
            request,
            message="Vous ne pouvez pas vous bloquer vous-même.",
            extra_tags="block_error")
        return redirect("users:following")
    if UserFollows.objects.filter(
            user=request.user,
            followed_user=user_to_manage
    ).exists():
        messages.error(
            request,
            message="Veuillez vous désabonner de cet utilisateur avant de le "
                    "bloquer.",
            extra_tags="block_error",
        )
        return redirect("users:following")
    try:
        if unblock:
            UserBlocked.objects.get(
                user=request.user,
                blocked_user=user_to_manage
            ).delete()
        else:
            UserBlocked.objects.create(
                user=request.user,
                blocked_user=user_to_manage
            )
    except UserBlocked.DoesNotExist:
        messages.error(
            request,
            "Vous ne bloquez pas cet utilisateur.",
            extra_tags="block_error"
        )
    except IntegrityError:
        messages.error(
            request,
            message="Vous bloquez déjà cet utilisateur.",
            extra_tags="block_error"
        )
        return redirect("users:following")
    return redirect("users:following")

users/templates/following.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
    <section class="d-flex flex-column align-items-center">
        <h3 class="h3 mb-5">Suivre ou bloquer d'autres utilisateurs</h3>
        <div class="container d-flex flex-column align-items-center mb-2">
            <h5 class="h5">Suivre</h5>
            <form action="{% url 'users:follow_user' %}" method="post"
                  class="d-flex justify-content-center align-items-center gap-4 mb-3 d-flex align-items-center">
                {% csrf_token %}
                {% bootstrap_form follow_form layout='inline' %}
                <button class="btn btn-primary" type="submit">Suivre</button>
            </form>
            {% if messages %}
                {% for message in messages %}
                    {% if message.tags == "follow_error error" %}
                        <div class="alert alert-danger"> {{ message }}</div>
                    {% endif %}
                {% endfor %}
            {% endif %}
        </div>
        <div class="container d-flex flex-column align-items-center mb-5">
            <h5 class="h5">Bloquer</h5>
            <form action="{% url 'users:block_user' %}" method="post"
                  class="d-flex justify-content-center align-items-center gap-4 mb-3 d-flex align-items-center">
                {% csrf_token %}
                {% bootstrap_form block_form layout='inline' %}
                <button class="btn btn-primary" type="submit">Bloquer</button>
            </form>
            {% if messages %}
                {% for message in messages %}
                    {% if message.tags == "block_error error" %}
                        <div class="alert alert-danger"> {{ message }}</div>
                    {% endif %}
                {% endfor %}
            {% endif %}
        </div>
        <div class="container d-flex flex-column align-items-center gap-2 mb-5">
            <h3 class="h3"> Abonnements</h3>
            {% for following_user in user.following.all %}
                <form action="{% url 'users:follow_user' unfollow=True %}"
                      method="post"
                      class="d-flex gap-4 align-items-baseline">
                    {% csrf_token %}
                    <p> {{ following_user.followed_user.username }}</p>
                    <input type="hidden" name="username"
                           value="{{ following_user.followed_user.username }}"
                           readonly
                           class="form-control"/>
                    <button class="btn btn-primary" type="submit">Se
                        désabonner
                    </button>
                </form>
            {% endfor %}
        </div>
        <div class="container d-flex flex-column align-items-center gap-2 mb-5">
            <h3 class="h3"> Abonnés </h3>
            {% for follower in followers %}
                <div class="d-flex justify-content-between align-items-center w-100 border rounded p-2">
                    {{ follower.username }}
                </div>
            {% endfor %}
        </div>
        <div class="container d-flex flex-column align-items-center gap-2 mb-5">
            <h3 class="h3">Bloqués</h3>
            {% for blocked_user in user.user.all %}
                <form action="{% url 'users:block_user' unblock=True %}"
                      method="post"
                      class="d-flex gap-4 align-items-baseline">
                    {% csrf_token %}
                    {{ unblock_form.is_unblock_form }}
                    <p> {{ blocked_user.blocked_user.username }}</p>
                    <input type="hidden" name="username"
                           value="{{ blocked_user.blocked_user.username }}"
                           readonly class="form-control"/>
                    <button class="btn btn-primary" type="submit">Débloquer
                    </button>
                </form>
            {% endfor %}
        </div>
    </section>
{% endblock content %}

users/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <section class="login py-5">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <h2 class="h3 mb-3">
                        Inscrivez-vous !
                    </h2>
                    <a class="btn btn-outline-primary text-decoration-none"
                       href="{% url 'users:signup' %}">S'inscrire</a>
                </div>
                <div class="col-md-6">
                    <h1 class="h3 mb-4">Se connecter</h1>
                    <form action="" method="post">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="mb-3">
                                {{ field.label_tag }}
                                {{ field }}
                                {% if field.help_text %}
                                    <small class="form-text text-muted">{{ field.help_text }}</small>
                                {% endif %}
                                {% if field.errors %}
                                    <div class="invalid-feedback">
                                        {{ field.errors|striptags }}
                                    </div>
                                {% endif %}
                            </div>
                        {% endfor %}
                        <button class="btn btn-primary" type="submit">Se
                            connecter
                        </button>
                    </form>
                    {% if message %}
                        <div class="alert alert-danger mt-4">{{ message }}</div>
                    {% endif %}
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

users/templates/signup.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% block content %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <h1 class="text-center mb-4">Inscription</h1>
                <form action="" method="post" novalidate class="mb-3">
                    {% csrf_token %}
                    {% bootstrap_form user_form layout='floating' %}
                    <input type="submit" value="S'inscrire"
                           class="btn btn-primary w-100">
                </form>
                <div class="text-center">
                    <a href="{% url 'users:login' %}"
                       class="d-block mt-3 text-decoration-none">Retourner</a>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}