litrevu/urls.py
from django.contrib import admin
from django.urls import path, include
from users import urls as users_urls
from litrevu_management import urls as litrevu_urls
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include(users_urls)),
    path('', include(litrevu_urls))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

litrevu_management/urls.py
from django.urls import path
import litrevu_management.views as views

app_name = "litrevu"

urlpatterns = [
    path('', views.home, name='home'),
    path('review/ticket/create/', views.create_ticket, name='create_ticket'),
    path('review/ticket/update/<int:ticket_id>', views.create_ticket,
         name='update_ticket'),
    path('review/ticket/delete/<int:ticket_id>', views.delete_ticket,
         name='delete_ticket'),
    path('review/create/', views.create_review, name='create_review'),
    path('review/create/<int:ticket_id>', views.create_review_from_ticket,
         name='create_review_from_ticket'),
    path('review/update/<int:review_id>', views.update_review,
         name='update_review'),
    path('review/delete/<int:review_id>', views.delete_review,
         name='delete_review'),
    path('posts/', views.posts, name='posts'),
]

users/urls.py
from django.urls import path
import users.views

app_name = "users"

urlpatterns = [
    path('login/', users.views.user_login, name='login'),
    path('signup/', users.views.signup, name='signup'),
    path('logout/', users.views.logout_user, name='logout'),
    path('following/', users.views.following, name='following'),
    path('following/follow/', users.views.follow_user, name='follow_user'),
    path(
        'following/follow/<unfollow>',
        users.views.follow_user,
        name='follow_user'
    ),
    path('following/block/', users.views.block_user, name='block_user'),
    path(
        'following/block/<unblock>/',
        users.views.block_user,
        name='block_user'
    ),
]

litrevu_management/models.py
from django.db import models
from litrevu import settings
from django.core.validators import MinValueValidator, MaxValueValidator


class Ticket(models.Model):
    """
    Ticket represents a ticket in our application
    """
    title = models.CharField(max_length=128)
    description = models.TextField(max_length=2048, blank=True)
    image = models.ImageField(null=True, blank=True, upload_to="images/")
    time_created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )


class Review(models.Model):
    """
    Review represents a review in our application
    """
    ticket = models.ForeignKey(to=Ticket, on_delete=models.CASCADE)
    rating = models.PositiveSmallIntegerField(
        validators=[
            MinValueValidator(0),
            MaxValueValidator(5),
        ]
    )
    user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    headline = models.TextField(max_length=8192, blank=True)
    body = models.TextField(max_length=8192, blank=True)
    time_created = models.DateTimeField(auto_now_add=True)

litrevu_management/forms.py
from django import forms
from litrevu_management.models import Ticket, Review

RATING_CHOICES = [(value, str(value)) for value in range(6)]


class TicketForm(forms.ModelForm):
    """
    TicketForm is used to manage the creation of a ticket received from
    the front in our django application.
    """

    class Meta:
        model = Ticket
        fields = ['title', 'description', 'image']
        labels = {
            'title': 'Titre',
            'description': 'Description',
            'image': 'Image',
        }
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.TextInput(attrs={'class': 'form-control'}),
        }


class ReviewForm(forms.ModelForm):
    """
    ReviewForm is used to manage the creation of a ticket received from the
    front in our Django Application.
    """

    class Meta:
        model = Review
        fields = ['headline', 'rating', 'body']
        labels = {
            'headline': 'Titre',
            'rating': 'Note',
            'body': 'Description',
        }
        widgets = {
            'rating': forms.RadioSelect(choices=RATING_CHOICES),
            'headline': forms.TextInput(attrs={'class': 'form-control'}),
            'body': forms.TextInput(attrs={'class': 'form-control'}),
        }

litrevu_management/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from litrevu_management import forms
from litrevu_management.models import Ticket, Review
from users.models import UserFollows


@login_required
def home(request):
    items_to_display = []
    following_relations = UserFollows.objects.filter(user=request.user)
    for following in following_relations:
        items_to_display.extend(
            Ticket.objects.filter(user=following.followed_user))
        items_to_display.extend(
            Review.objects.filter(user=following.followed_user))
    personal_tickets = Ticket.objects.filter(user=request.user)
    personal_reviews = Review.objects.filter(user=request.user)
    for personal_ticket in personal_tickets:
        review_associated = personal_ticket.review_set.all()
        items_to_display.extend(review_associated)
    items_to_display.extend(personal_tickets)
    items_to_display.extend(personal_reviews)
    items_to_display = list(set(items_to_display))
    sorted_items = sorted(
        items_to_display,
        key=lambda item: item.time_created,
        reverse=True
    )
    return render(
        request,
        'home.html',
        context={
            "items": sorted_items
        }
    )


@login_required
def posts(request):
    items_to_display = []
    items_to_display.extend(Ticket.objects.filter(user=request.user))
    items_to_display.extend(Review.objects.filter(user=request.user))
    sorted_items = sorted(
        items_to_display,
        key=lambda item: item.time_created,
        reverse=True
    )
    return render(
        request,
        'posts.html',
        context={
            'items': sorted_items,
        }
    )


@login_required
def create_ticket(request, ticket_id=None):
    is_updating = ticket_id is not None
    try:
        ticket = Ticket.objects.get(id=ticket_id)
    except Ticket.DoesNotExist:
        ticket = None
    ticket_form = forms.TicketForm(
        request.POST if request.method == "POST" else None,
        request.FILES if request.method == "POST" else None,
        instance=ticket if ticket else None,
    )
    if request.method == "POST" and ticket_form.is_valid():
        ticket = ticket_form.save(commit=False)
        ticket.user = request.user
        ticket.save()
        return redirect('litrevu:posts')
    return render(
        request,
        'create_ticket.html',
        context={
            "is_updating": is_updating,
            "ticket_form": ticket_form,
        },
    )


@login_required
def update_ticket(request, ticket_id):
    ticket = get_object_or_404(Ticket, id=ticket_id, user=request.user)
    edit_ticket = forms.TicketForm(instance=ticket)
    if request.method == "POST":
        edit_ticket = forms.TicketForm(
            request.POST,
            request.FILES,
            instance=ticket,
        )
        if edit_ticket.is_valid():
            edit_ticket.save()
            return redirect('litrevu:home')
    return render(
        request,
        template_name='update_ticket.html',
        context={
            'edit_ticket_form': edit_ticket,
            'ticket': ticket,
        }
    )


@login_required
def delete_ticket(request, ticket_id):
    ticket = get_object_or_404(Ticket, id=ticket_id)
    if request.user != ticket.user:
        raise PermissionDenied

    ticket.delete()
    return redirect('litrevu:posts')


@login_required
def create_review(request):
    ticket_form = forms.TicketForm(
        request.POST if request.method == "POST" else None,
        request.FILES if request.method == "POST" else None
    )
    review_form = forms.ReviewForm(
        request.POST if request.method == "POST" else None)
    if (request.method == "POST" and ticket_form.is_valid() and
            review_form.is_valid()):
        ticket = ticket_form.save(commit=False)
        ticket.user = request.user
        review = review_form.save(commit=False)
        review.ticket = ticket
        review.user = request.user
        ticket.save()
        review.save()
        return redirect('litrevu:home')
    return render(
        request,
        'create_review.html',
        context={
            "ticket_form": ticket_form,
            "review_form": review_form,
        }
    )


@login_required
def create_review_from_ticket(request, ticket_id):
    ticket = Ticket.objects.get(pk=ticket_id)
    review_form = forms.ReviewForm(
        request.POST if request.method == "POST" else None)
    if request.method == "POST" and review_form.is_valid():
        review = review_form.save(commit=False)
        review.ticket = ticket
        review.user = request.user
        review.save()
        return redirect('litrevu:home')
    return render(
        request,
        template_name='review_from_ticket.html',
        context={
            'ticket': ticket,
            'review_form': review_form,
        }
    )


@login_required
def update_review(request, review_id):
    review = get_object_or_404(Review, id=review_id)
    if request.user != review.user:
        raise PermissionDenied
    update_review_form = forms.ReviewForm(instance=review)
    if request.method == "POST":
        update_review_form = forms.ReviewForm(request.POST, instance=review)
        if update_review_form.is_valid():
            update_review_form.save()
            return redirect('litrevu:posts')
    return render(
        request,
        template_name='update_review.html',
        context={
            'update_review_form': update_review_form,
            'review': review,
        }
    )


@login_required
def delete_review(request, review_id):
    review = get_object_or_404(Review, id=review_id)
    if request.user != review.user:
        raise PermissionDenied
    review.delete()
    return redirect('litrevu:posts')

litrevu_management/templates/create_review.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
    <div class="d-flex justify-content-center">
        <h2 class="h2">Créer une critique</h2>
    </div>
    <form class="p-4" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-4">
            <h5 class="h5"> Création du ticket:</h5>
            {% bootstrap_form ticket_form layout='floating' %}
        </div>
        <div>
            <h5 class="h5"> Création de la critique:</h5>
            {% bootstrap_field review_form.headline layout='floating' %}
        </div>
        <div class="d-flex mb-3 gap-4">
            Note :
            {% for choice in review_form.rating %}
                {{ choice }}
            {% endfor %}
        </div>
        {% bootstrap_field review_form.body layout='floating' %}
        {% bootstrap_button button_type='submit' content='Soumettre' %}
        <a class="btn btn-danger" href="{% url 'litrevu:home' %}">Annuler</a>
    </form>
{% endblock content %}

litrevu_management/templates/create_ticket.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
    <div class="d-flex justify-content-center m-4">
        {% if is_updating %}
            <h2 class="h2">Modifier un ticket</h2>
        {% else %}
            <h2 class="h2">Créer un ticket</h2>
        {% endif %}
    </div>
    <form class="px-4 py-4" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in ticket_form %}
            {% if field.is_hidden %}
                {{ field }}
            {% else %}
                {% if field.name != 'image' %}
                    {% bootstrap_field field layout='floating' %}
                {% else %}
                    {% if field.value %}
                        <div class="form-group">
                            <div>
                                <img src="{{ field.value.url }}" class="img-thumbnail"
                                     alt="Image actuelle"/>
                            </div>
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" name="{{ field.name }}-clear">
                                    Supprimer l'image actuelle
                                </label>
                            </div>
                        </div>
                    {% else %}
                        {% bootstrap_field field layout='floating' %}
                    {% endif %}
                {% endif %}
            {% endif %}
        {% endfor %}
        <button type="submit" class="btn btn-primary">
            {% if is_updating %}Modifier{% else %}Créer{% endif %}
        </button>
        <a class="btn btn-danger" href="{% url 'litrevu:home' %}">Annuler</a>
    </form>
{% endblock content %}

litrevu_management/templates/home.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block content %}
    <section class="container d-flex justify-content-center gap-4 align-items-center mb-4 mt-4  ">
        <a class="btn btn-primary" href="{% url 'litrevu:create_review' %}">Créer une critique</a>
        <a class="btn btn-primary" href="{% url 'litrevu:create_ticket' %}">Demander une critique</a>
    </section>
    {% if items|length == 0 %}
        <section>
            <p class="alert alert-info">Il n'y a pas encore de post à afficher.</p>
        </section>
    {% else %}
        <section class="container">
            {% for item in items %}
                {% if item|hasattr:"rating" %}
                    {% include "review.html" with review=item personal_view=False %}
                {% else %}
                    {% include "ticket.html" with ticket=item personal_view=False %}
                {% endif %}
            {% endfor %}
        </section>
    {% endif %}
{% endblock content %}

litrevu_management/templates/litrevu_404.html
{% extends 'base.html' %}
{% block content %}
    <h1>
        ERROR 404
    </h1>
{% endblock content %}

litrevu_management/templates/posts.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load custom_filters %}
{% block content %}
    <div class="d-flex justify-content-center mt-4">
        <h1 class="h1">Vos posts</h1>
    </div>
    {% if items|length == 0 %}
        <section>
            <p class="alert alert-info">Il n'y a pas encore de post à afficher.</p>
        </section>
    {% else %}
        <section class="container mb-4 mt-4">
            {% for item in items %}
                {% if item|hasattr:'rating' %}
                    {% include "review.html" with review=item personal_view=True %}
                {% else %}
                    {% include "ticket.html" with ticket=item personal_view=True %}
                {% endif %}
            {% endfor %}
        </section>
    {% endif %}
{% endblock content %}

litrevu_management/templates/review.html
<div class="card mb-4">
    <div class="card-body">
        <div class="mb-2">
            <div class="d-flex card-text text-muted justify-content-between">
                {% if request.user == review.user %}
                    <span>Vous avez publié une critique</span>
                {% else %}
                    <span>{{ review.user.username }} a publié une critique</span>
                {% endif %}
                <span class="text-muted">{{ review.ticket.time_created }}</span>
            </div>
        </div>
        <h5 class="card-title">
            {{ review.headline }} -
            {% for i in '01234'|make_list %}
                {% if forloop.counter <= review.rating %}
                    <i class="fas fa-star"></i>
                {% else %}
                    <i class="far fa-star"></i>
                {% endif %}
            {% endfor %} </h5>
        <p class="card-text">{{ review.body }}</p>
    </div>
    <div class="card-body border-top border-light-subtle">
        <div class="d-flex flex-column mb-4">
            <div class="d-flex justify-content-between">
                {% if request.user == review.ticket.user %}
                    <span class="card-title">Ticket - Vous&nbsp;</span>
                {% else %}
                    <span class="card-title">Ticket - {{ review.ticket.user.username }}&nbsp;</span>
                {% endif %}
                <span class="text-muted">{{ review.ticket.time_created }}</span>
            </div>
            <span> {{ review.ticket.title }}</span>
        </div>
        {% if review.ticket.image %}
            <img class="card-img-top img-fluid" src="{{ review.ticket.image.url }}"
                 alt=" image de la critique">
        {% endif %}
    </div>
    {% if not personal_view and request.user != review.ticket.user %}
        <div class="card-footer  d-flex justify-content-end">
            <a class="btn btn-primary"
               href="{% url 'litrevu:create_review_from_ticket' ticket_id=item.ticket.id %}">Créer une critique</a>
        </div>
    {% endif %}
    {% if personal_view %}
        <div class="card-footer">
            <div class="d-flex gap-4 justify-content-end">
                <a class="btn btn-primary"
                   href="{% url 'litrevu:update_review' review_id=review.id %}">Modifier</a>
                <form action="{% url 'litrevu:delete_review' review_id=review.id %}" method="post">
                    {% csrf_token %}
                    <button class="btn btn-danger" type="submit">Supprimer</button>
                </form>
            </div>
        </div>
    {% endif %}
</div>

litrevu_management/templates/review_from_ticket.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
    <div class="d-flex m-4 flex-column align-items-center">
        <h2 class="h2"> Créer une critique</h2>
        <span>Vous postez une réponse à : </span>
    </div>
    <div class="card col-md-6 offset-md-3">
        {% if ticket.image %}
            <img class="card-img-top img-fluid" src="{{ ticket.image.url }}" alt="image du ticket">
        {% endif %}
        <div class="card-body">
            <span> Ticket de {{ ticket.user.username }}</span>
            <h5 class="card-title">{{ ticket.title }}</h5>
            <p class="card-text"> {{ ticket.description }} </p>
        </div>
        <div class="card-footer">
            <p class="text-muted">
                {{ ticket.time_created }}
            </p>
        </div>
    </div>
    <form class="p-4" action="" method="post">
        {% csrf_token %}
        {% bootstrap_field review_form.headline layout='floating' %}
        <div class="d-flex mb-3 gap-4">
            Note :
            {% for choice in review_form.rating %}
                {{ choice }}
            {% endfor %}
        </div>
        {% bootstrap_field review_form.body layout='floating' %}
        {% bootstrap_button button_type='submit' content='Soumettre' %}
        <a class="btn btn-danger" href="{% url 'litrevu:home' %}">Annuler</a>
    </form>
{% endblock content %}

litrevu_management/templates/ticket.html
{% load custom_filters %}
<div class="card mb-4">
    <div class="card-body">
        <div class="mb-2">
            <div class="d-flex card-text text-muted justify-content-between">
                {% if personal_view %}
                    <span>Vous avez publié un ticket</span>
                {% else %}
                    {% if ticket.user == request.user %}
                        <span>Vous avez demandé une critique.</span>
                    {% else %}
                        <span>{{ ticket.user.username }} a demandé une critique.</span>
                    {% endif %}
                {% endif %}
                <span>{{ ticket.time_created }}</span>
            </div>
        </div>
        <h5 class="card-title">{{ ticket.title }}</h5>
        <span>{{ ticket.description }}</span>
    </div>
    {% if ticket.image %}
        <div class="container-sm p-4 d-flex justify-content-center overflow-hidden">
            <img class="img-fluid" src="{{ ticket.image.url }}"
                 alt="image du ticket">
        </div>
    {% endif %}
    {% if personal_view %}
        <div class="card-footer">
            <div class="d-flex gap-3 justify-content-end">
                <a class="btn btn-primary"
                   href="{% url 'litrevu:update_ticket' ticket_id=item.id %}">
                    Modifier
                </a>
                <form action="{% url 'litrevu:delete_ticket' ticket_id=item.id %}"
                      method="post">
                    {% csrf_token %}
                    <button class="btn btn-danger" type="submit">Supprimer
                    </button>
                </form>
            </div>
        </div>
    {% else %}
        {% if not ticket|has_review %}
            <div class="card-footer d-flex justify-content-end">
                <a class="btn btn-primary"
                   href="{% url 'litrevu:create_review_from_ticket' ticket_id=item.id %}">
                    Créer une critique
                </a>
            </div>
        {% endif %}
    {% endif %}
</div>

litrevu_management/templates/update_review.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
    <div class="card" style="width: 18rem">
        {% if review.ticket.image %}
            <img class="card-img-top img-fluid"
                 src="{{ review.ticket.image.url }}" alt="image du ticket">
        {% endif %}
        <div class="card-body">
            <h5 class="card-title">{{ review.ticket.title }}</h5>
            <p class="card-text"> {{ review.ticket.description }} </p>
        </div>
        <div class="card-footer">
            <p class="text-muted">
                {{ review.ticket.time_created }}
            </p>
        </div>
    </div>
    <form action="" method="post">
        {% csrf_token %}
        {% bootstrap_form update_review_form layout='floating' %}
        <button class="btn btn-primary" type="submit">Modifier</button>
        <a class="btn btn-danger" href="{% url 'litrevu:home' %}">Annuler</a>
    </form>
{% endblock content %}

litrevu_management/templates/update_ticket.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form edit_ticket_form layout='floating' %}
        {% if ticket.image %}
            <div style="width: 200px; height: 200px;">
                <img class="w-100" src="{{ ticket.image.url }}"
                     alt="image du ticket">
            </div>
        {% endif %}
        <button class="btn btn-primary" type="submit">Modifier</button>
        <a class="btn btn-danger" href="{% url 'litrevu:home' %}">Annuler</a>
    </form>
{% endblock content %}