litrevu/urls.py
from django.contrib import admin
from django.urls import path, include
from users import urls as users_urls
from litrevu_management import urls as litrevu_urls
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include(users_urls)),
    path('', include(litrevu_urls))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

litrevu_management/urls.py
from django.urls import path
import litrevu_management.views as views

app_name = "litrevu"

urlpatterns = [
    path('', views.home, name='home'),
    path('review/ticket/create/', views.create_ticket, name='create_ticket'),
    path('review/ticket/update/<int:ticket_id>', views.create_ticket,
         name='update_ticket'),
    path('review/ticket/delete/<int:ticket_id>', views.delete_ticket,
         name='delete_ticket'),
    path('review/create/', views.create_review, name='create_review'),
    path('review/create/<int:ticket_id>', views.create_review_from_ticket,
         name='create_review_from_ticket'),
    path('review/update/<int:review_id>', views.update_review,
         name='update_review'),
    path('review/delete/<int:review_id>', views.delete_review,
         name='delete_review'),
    path('posts/', views.posts, name='posts'),
]

users/urls.py
from django.urls import path
import users.views

app_name = "users"

urlpatterns = [
    path('login/', users.views.user_login, name='login'),
    path('signup/', users.views.signup, name='signup'),
    path('logout/', users.views.logout_user, name='logout'),
    path('following/', users.views.following, name='following'),
    path('following/follow/', users.views.follow_user, name='follow_user'),
    path(
        'following/follow/<unfollow>',
        users.views.follow_user,
        name='follow_user'
    ),
    path('following/block/', users.views.block_user, name='block_user'),
    path(
        'following/block/<unblock>/',
        users.views.block_user,
        name='block_user'
    ),
]

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
    <title>Litrevu</title>
</head>
<body class="d-flex flex-column min-vh-100">
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        {% if user.is_authenticated %}
            <div class="container-fluid">
                <div class="mx-auto">
                    <a class="navbar-brand" href="{% url 'litrevu:home' %}">LITREVIEW</a>
                </div>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'litrevu:home' %}">Flux</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'litrevu:posts' %}">Posts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:following' %}">Abonnements</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:logout' %}">Se déconnecter</a>
                        </li>
                    </ul>
                </div>
            </div>
        {% else %}
            <div class="container d-flex justify-content-center">
                <a class="navbar-brand" href="#">LITREVIEW</a>
            </div>
        {% endif %}
    </nav>
</header>
<main class="flex-grow-1">
    {% block content %} {% endblock content %}
</main>
<footer class="bg-light py-3">
    <div class="container text-center">
        <p class="mb-0">Litrevu tout droits réservés.</p>
    </div>
</footer>
</body>
</html>